### ISSUE TITLE
Upgrade React to 17, fix other dependencies, and make sure nothing breaks, also enable strict mode

### ISSUE THREAD

**Issue by JoshuaVSherman** [WebJamApps/breakpointministries#100]
![image](https://user-images.githubusercontent.com/13340120/119131561-9f97df80-ba07-11eb-93f7-73378a67b5c8.png)

**Comment by JoshuaVSherman** [comment]
@Unesdala FYI, TinyMCE broke and I had to downgrade it

**Comment by JoshuaVSherman** [comment]
@Unesdala is this one already done? if so please drag it to close, thanks

**Comment by Unesdala** [comment]
@JoshuaVSherman - It's upgraded to 17, still need to enable strict mode and possibly fix a few things with that.
