### ISSUE TITLE
Fix Blog Editor wysiwyg

### ISSUE THREAD

**Issue by JoshuaVSherman** [WebJamApps/breakpointministries#56]
- [x] on mobile, when manipulating text by trying to make text bold, italics or underlined, it does not save the changes when posting the blog. Also, the highlight text feature doesn't function.  **Tested on Josh's cellphone, no issue**
- [x] Fix width of Editor so it has overflow x on cellphone with a fixed width, and remains 100% width when wider screen-sizes

**Comment by Unesdala** [comment]
@JoshuaVSherman - The PR I have up now should fix this. The editor bar on smaller screens is draggable (For the full set of edit buttons), and it fills the screen nicely.
