### ISSUE TITLE
Blog editor reversing text

### ISSUE THREAD

**Issue by Unesdala** [WebJamApps/breakpointministries#99]
![image](https://user-images.githubusercontent.com/25317100/117232768-d529af80-adef-11eb-8b9a-9834846a8e0f.png)

**Comment by JoshuaVSherman** [comment]
@Unesdala working fine on changeinchrist.org  testing it locally now on develop branch

**Comment by JoshuaVSherman** [comment]
@Unesdala tested locally on develop branch, no issues, closing this
